version: '3.8'
services:
  server:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    container_name: showusthedata_api
    env_file:
      - .env
    volumes:
      - ./src/:/app/
    ports:
      - 8000:8000
